# sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"
    #- "3.2"

virtualenv:
  system_site_packages: true

# install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install gmsh python-numpy
  - sudo apt-get -y install pandoc

install:
  # Work around travis bug <https://github.com/travis-ci/travis-ci/issues/4948>
  - export PATH="/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.5.1.linux.amd64/bin:/home/travis/.local/bin:/usr/local/rvm/gems/ruby-2.2.3/bin:/usr/local/rvm/gems/ruby-2.2.3@global/bin:/usr/local/rvm/rubies/ruby-2.2.3/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/usr/local/phantomjs:/home/travis/perl5/perlbrew/bin:/home/travis/.nvm/versions/node/v4.1.2/bin:./node_modules/.bin:/usr/local/maven-3.1.1/bin:/usr/local/gradle/bin:/usr/local/clang-3.5.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/usr/local/rvm/bin"
  - pip install -r requirements.txt
  # Alternative: setup.py install.
  # Using pip makes sure that the package is pip-compatible, too.
  - pip install .
  - pip install coverage

# run tests
script:
  - nosetests --with-coverage --cover-package=pygmsh

after_success:
  - bash <(curl -s https://codecov.io/bash)
