# sudo: false
sudo: required
dist: trusty

language: python

python:
    - "2.7"
    #- "3.2"

virtualenv:
  system_site_packages: true

# install dependencies
before_install:
  - sudo apt-add-repository -y ppa:nschloe/gmsh-backports
  - sudo apt-get update -qq
  - sudo apt-get -y install gmsh python-numpy
  - sudo apt-get -y install pandoc
  - pip install pytest pytest-cov

install:
  - pip install -r test_requirements.txt
  - pip install .
  - pip install coverage

# run tests
script:
  - cd test/ && pytest --cov=pygmsh

after_success:
  - bash <(curl -s https://codecov.io/bash)
